apiVersion: apps/v1
kind: Deployment
metadata:
  name: gemini
  namespace: gpt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gemini
  template:
    metadata:
      labels:
        app: gemini
    spec:
      containers:
        - name: gemini
          image: babaohuang/geminiprochat:latest
          imagePullPolicy: "Always"
          command: ["/bin/sleep", "3650d"]
          env:
            - name: GEMINI_API_KEY
              value: ""
            - name: http_proxy
              value: "https://192.168.64.1:1087"
            - name: https_proxy
              value: "https://192.168.64.1:1087"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: gemini
  namespace: gpt
spec:
  type: NodePort
  ports:
   - port: 3000
     nodePort: 30091
  selector:
   app: gemini
