apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: database
stringData:
  MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "0"
  MARIADB_ROOT_PASSWORD: "root@"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mariadb-pv-volume
  namespace: database
  labels:
    app: mariadb
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /Users/Jing/Code/data/db/mariadb/data
    type: Directory
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mariadb-pv-claim
  namespace: database
  labels:
    app: mariadb
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      volumes:
      containers:
        - name: mariadb
          image: mariadb:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 3306
          envFrom:
            - secretRef:
                name: mariadb-secret
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mariadb-volumes
      volumes:
        - name: mariadb-volumes
          persistentVolumeClaim:
            claimName: mariadb-pv-claim
